name: macOS VNC with ngrok

on:
  push:
    branches:
      - main  # Trigger on push to main branch, you can adjust as needed
  workflow_dispatch: # Allow manual trigger

jobs:
  setup-vnc-ngrok:
    runs-on: macos-14  # You need a macOS runner

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew install tigervnc ngrok

      - name: Start VNC server
        run: |
          vncserver :1  # Start VNC server on port 5901 && ngrok authtoken 2rHguGiAlDVeEp6jIbkzCnPxXhb_3Mw82pryyzB9hqEhyeDpT

      - name: Start ngrok
        run: |
          ngrok tcp 5901 > /tmp/ngrok.log &
          sleep 5
          cat /tmp/ngrok.log | grep -m 1 "tcp://"  # Extract ngrok public URL
          
      - name: Print ngrok URL
        run: |
          ngrok_url=$(cat /tmp/ngrok.log | grep -m 1 "tcp://" | awk '{print $1}')
          echo "VNC server is available at $ngrok_url"
