name: macOS VNC with ngrok

on:
  push:
    branches:
      - main  # Trigger on push to main branch, you can adjust as needed
  workflow_dispatch: # Allow manual trigger

jobs:
  setup-vnc-ngrok:
    runs-on: macos-latest  # You need a macOS runner

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew install x11vnc ngrok && ngrok authtoken 2rHguGiAlDVeEp6jIbkzCnPxXhb_3Mw82pryyzB9hqEhyeDpT  # Install x11vnc instead of TigerVNC

      - name: Start VNC server
        run: |
          x11vnc -display :0 -nopw -listen localhost -xkb  # Start the x11vnc server

      - name: Start ngrok
        run: |
          ngrok tcp 5900 > /tmp/ngrok.log &  # Expose the VNC server on port 5900
          sleep 5
          cat /tmp/ngrok.log | grep -m 1 "tcp://"  # Extract ngrok public URL
          
      - name: Print ngrok URL
        run: |
          ngrok_url=$(cat /tmp/ngrok.log | grep -m 1 "tcp://" | awk '{print $1}')
          echo "VNC server is available at $ngrok_url"

